### ISSUE TITLE
[Request] Angular version

### ISSUE THREAD

**Issue by iameduardod** [adobe/aem-contrib-wcm-components#4]
It would be awesome to get an Angular version of these components!

**Comment by niekraaijmakers** [comment]
Would be awesome indeed... I will see what I can do, as I am not as good angular as with React. If anybody wants to help, send me a message! Somebody must be having time now? :)

**Comment by thesurenk** [comment]
@niekraaijmakers i can help with Angular

**Comment by niekraaijmakers** [comment]
Would be cool :) I am working (slowly) on an Angular version. I can push it to a branch and you can do pull requests to it (without rigorous reviews). Let's figure out some way to get in touch.

**Comment by iameduardod** [comment]
Any update on this?! @ksurendra

**Comment by thesurenk** [comment]
> Any update on this?! @ksurendra 

Not yet. Will update here

**Comment by niekraaijmakers** [comment]
Same here. Lately I have been working on billable projects which take priority. I am going to look if I have some time available to contribute in the comings months. If I have any time left, this has priority for me!

**Comment by niekraaijmakers** [comment]
Angular version is now provided! https://github.com/adobe/aem-contrib-wcm-components/tree/feature/angular-wrapper
