### ISSUE TITLE
Switch to more inclusive language

### ISSUE THREAD

**Issue by macdonst** [adobe/aem-contrib-wcm-components#5]
Could you please take some time in the next few days to make changes to some terminology in your repos and content as much as is possible:

- Whitelist/blacklist to Allowed List and Blocked List (or Approve List/Deny List - some software uses this instead) respectively. Google and many developers are formalizing allowlist and blocklist. You might want to lobby for those terms to be used in the UI.
- Master/Slave to master and replica (or subordinate, if that makes more sense) respectively.

If you cannot remove the term because the writing for example reflects the UI or the code, please make a note and send me an email to Grp-opensourceoffice@adobe.com so we can bring it that team’s attention. Thanks for your efforts in this matter.

**Comment by msagolj** [comment]
@macdonst Searching for mentioned keywords gives:
- Whitelist/Blacklist: only used for parameter names in [config file](https://github.com/adobe/aem-contrib-wcm-components/blob/f4bef153928a75200b521dffc8ad6ee453488e6c/ui.apps/.stylelintrc.yaml) for the stylelint (https://stylelint.io) tool. So its outside of our control.
- Master/Slave: there is no concept named like this in the code.
- *master* branch: not required to be changed if I understand correctly. If yes, this is a bigger effort as it affects other repos, scripts, builds, processes etc. and requires coordination between different teams.

**Comment by macdonst** [comment]
@msabramo Thanks for identifying that https://stylelint.io is the dependency causing the positive scan result. I'm adding it to my list of open source projects to reach out to.
